name: Serie A M3U8 Updater

on:
  schedule:
    - cron: '0 12 * * *'  # Esegue ogni giorno alle 12:00 UTC
  workflow_dispatch:  # Permette l'esecuzione manuale

permissions:
  contents: write

jobs:
  update-m3u8:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run updater script
      run: |
        python serie_a_m3u8_updater_fixed.py
        
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Aggiornamento giornaliero lista Serie A"
        file_pattern: serie_a.m3u8
