# Workflow per l'Aggiornamento Automatico della Playlist Serie A con yt-dlp
# Questo workflow esegue lo script Python giornalmente per estrarre gli URL degli stream
# utilizzando yt-dlp, uno strumento specializzato nell'estrazione di contenuti video.

name: Auto Update Serie A con yt-dlp

on:
  schedule:
    - cron: '0 12 * * *'  # Esegue ogni giorno alle 12:00 UTC
  workflow_dispatch:  # Permette l'esecuzione manuale

permissions:
  contents: write  # Necessario per committare le modifiche

jobs:
  update-m3u8:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install yt-dlp and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 yt-dlp
        
    - name: Run ytdlp script
      run: |
        python serie_a_ytdlp_extractor.py
        
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Aggiornamento giornaliero lista Serie A"
        file_pattern: serie_a.m3u8
